// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Potestas.ORM.CodeFirstAproach;

namespace Potestas.ORM.CodeFirstAproach.Migrations
{
    [DbContext(typeof(ObservationContext))]
    [Migration("20191119114335_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Potestas.ORM.CodeFirstAproach.Models.Coordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("X")
                        .HasColumnType("float(53)");

                    b.Property<double>("Y")
                        .HasColumnType("float(53)");

                    b.HasKey("Id");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("Potestas.ORM.CodeFirstAproach.Models.EnergyObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoordinateId");

                    b.Property<double>("EstimatedValue")
                        .HasColumnType("float(53)");

                    b.Property<DateTime>("ObservationTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CoordinateId");

                    b.ToTable("EnergyObservations");
                });

            modelBuilder.Entity("Potestas.ORM.CodeFirstAproach.Models.EnergyObservation", b =>
                {
                    b.HasOne("Potestas.ORM.CodeFirstAproach.Models.Coordinate", "Coordinate")
                        .WithMany("EnergyObservations")
                        .HasForeignKey("CoordinateId");
                });
#pragma warning restore 612, 618
        }
    }
}
